### ISSUE TITLE
[PE-D] help command is incomplete

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-4/tp#179] opened 2022-04-01 17:48 UTC
The `help` command does not show the command list as described in the UG. 

![image.png](https://raw.githubusercontent.com/honganhcs/ped/main/files/c036e1f9-5c06-4da8-abc2-c6bda0cf07cf.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: honganhcs/ped#10

**Comment by zhongfu** [comment] 2022-04-01 17:52
dupe of #165

**Closed by zhongfu** 2022-04-01 17:52 UTC
