### ISSUE TITLE
List of persons appears to be blocked by some UI object occasionally

### ISSUE THREAD

**Issue by Spyobird** [AY2122S2-CS2103T-T11-4/tp#126] opened 2022-03-31 15:26 UTC
![ui_bug1](https://user-images.githubusercontent.com/4799598/161091525-b952993c-124d-4713-8226-2da7f336eec3.PNG)
Only shows person 1.

Seems to be sometimes affected by resizing.

Not sure if list of jobs behaves similarly

**Comment by ian-from-dover** [comment] 2022-04-03 13:20
dupe of #195

**Closed by ian-from-dover** 2022-04-03 13:20 UTC
Labels: type.Bug
