### ISSUE TITLE
[ian's branch at the moment] Cannot `add` people, even after `clear`ing

### ISSUE THREAD

**Issue by ian-from-dover** [AY2122S2-CS2103T-T11-4/tp#105] opened 2022-03-29 16:23 UTC
Input: `add n/Sim Wei En p/88124412 e/weien@stfhub.org a/12 Haw Par Villa, S221053 r/12 t/Wifi t/Electrician t/Infrastructure t/Welding`

![Screenshot 2022-03-30 at 12 20 11 AM](https://user-images.githubusercontent.com/62384984/160659378-d2bf0b01-f38d-4d06-81f5-1c998e6bb1dc.png)

Exception
INFO: ----------------[USER COMMAND][add n/Sim Wei En p/88124412 e/weien@stfhub.org a/12 Haw Par Villa, S221053 r/12 t/Wifi t/Electrician t/Infrastructure t/Welding]
Mar 30, 2022 12:20:10 AM peoplesoft.ui.MainWindow executeCommand
INFO: Invalid command: add n/Sim Wei En p/88124412 e/weien@stfhub.org a/12 Haw Par Villa, S221053 r/12 t/Wifi t/Electrician t/Infrastructure t/Welding
Mar 30, 2022 12:22:07 AM peoplesoft.logic.LogicManager execute

**Comment by Spyobird** [comment] 2022-03-30 18:58
If it is caused by what I think, it may be resolved by the changes in #106

**Closed** 2022-03-31 13:44 UTC
Labels: type.Bug, severity.Low
